function m(b,a,c,d){b.m.pb(b.tb,a,c,d)}function n(b,a,c,d){b.m.ba?m(b,a,c,d):b.m.Te()._OnMessageFromDOM({type:"event",component:b.tb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.m.B(b.tb,a,c)}function v(b,a){for(const [c,d]of a)q(b,c,d)}function w(b){b.Xb||(b.m.Dc(b.je),b.Xb=!0)}window.jb=class{constructor(b,a){this.m=b;this.tb=a;this.Xb=!1;this.je=()=>this.Qa()}qd(){}Qa(){}};
window.Ef=class{constructor(){this.ua=-1}j(){-1!==this.ua&&(self.clearTimeout(this.ua),this.ua=-1)}};"use strict";class aa{constructor(b){this.wb=b;this.Sc=!1;this.$c=!0;this.yb=this.pa=this.md=-1}}
function ca(b,a){const c=a.elementId,d=b.ud(c,a),e=new aa(d);b.Ia.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.$c=!!a.isVisible;d.addEventListener("focus",()=>{da(b,"elem-focused",c)});d.addEventListener("blur",()=>{da(b,"elem-blurred",c)});const f=a.htmlIndex;e.md=f;e.yb=a.htmlZIndex;b.Ta&&(a=b.m.tc(f),e.pa=a,b.m.Nb(a).appendChild(d))}function ea(b,a){q(b,"get-element",c=>{const d=x(b,c.elementId);return a(d,c)})}
function x(b,a){b=b.Ia.get(a);if(!b)throw Error(`no element with id ${a}`);return b.wb}function da(b,a,c){var d;d||(d={});d.elementId=c;m(b,a,d)}
window.sc=class extends self.jb{constructor(b){super(b,"progress-bar");this.Ia=new Map;this.Ta=!0;v(this,[["create",a=>ca(this,a)],["destroy",a=>{a=a.elementId;const c=x(this,a);this.Ta&&c.parentElement.removeChild(c);this.Ia.delete(a)}],["set-visible",a=>{if(this.Ta){var c=this.Ia.get(a.elementId),d=c.wb;c.Sc?d.style.display=a.isVisible?"":"none":c.$c=!!a.isVisible}}],["update-position",a=>{if(this.Ta){var c=this.Ia.get(a.elementId),d=c.wb,e=this.m;d.style.left=a.left+"px";d.style.top=a.top+"px";
d.style.width=a.width+"px";d.style.height=a.height+"px";var f=a.fontSize;null!==f&&(d.style.fontSize=f+"em");f=a.htmlIndex;c.md=f;f=e.tc(f);f!==c.pa&&(d.remove(),e.Nb(f).appendChild(d),c.pa=f,e.Mc());a=a.htmlZIndex;a!==c.yb&&(c.yb=a,e.Mc());c.Sc||(c.Sc=!0,c.$c&&(d.style.display=""))}}],["update-state",a=>{const c=x(this,a.elementId);this.Cc(c,a)}],["focus",a=>{const c=x(this,a.elementId);a.focus?c.focus():c.blur()}],["set-css-style",a=>{const c=x(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?
c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{x(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{x(this,a.elementId).removeAttribute(a.name)}]]);ea(this,a=>a)}ud(){throw Error("required override");}Cc(){throw Error("required override");}};"use strict";const fa=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent),ha=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);
let ia=0;function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.uf?new Promise(c=>{const d="c3_resolve_"+ia;++ia;self[d]=c;a.textContent=b.yf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ja(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let A=new Audio;
const ka={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function la(b){b=await ma(b);return(new TextDecoder("utf-8")).decode(b)}
function ma(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const B=[];let D=0;window.RealFile=window.File;const E=[],F=new Map,qa=new Map;let ra=0;const sa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");sa.push(b)};const ta=new Set(["cordova","playable-ad","instant-games"]);let ua=!1;
window.Pa=class b{constructor(a){this.ba=a.Af;this.ya=null;this.aa="";this.cb=a.xf;this.Lb={};this.Xa=this.va=null;this.Va=[];this.ma=null;this.Xd=!0;this.M=[];this.fd=[];this.gd=!1;this.ke=()=>this.Re();this.Wc=!1;this.Rd=0;this.Ab=null;this.bb=-1;this.qf=()=>this.bf();this.Ib=new Set;this.nd=null;this.le=[];this.A=a.me;this.Yb="file"===location.protocol.substr(0,4);if("playable-ad"===this.A||"instant-games"===this.A)this.ba=!1;ha&&(this.ba=!1);if("cordova"===this.A&&this.ba&&y){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ba=!1)}this.Na()?self.chrome.webview.addEventListener("message",c=>this.Gd(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.Gd(c));this.ac=this.ra=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.ff(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Xe());this.B("runtime","cordova-fetch-local-file",c=>this.Ye(c));this.B("runtime","create-job-worker",()=>this.Ze());this.B("runtime","send-wrapper-extension-message",c=>this.ef(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.Ed(a)):this.Ed(a)}j(){this.Ec();this.ya&&(this.ya=this.ya.onmessage=null);this.va&&(this.va.terminate(),this.va=null);this.Xa&&(this.Xa.j(),this.Xa=null);for(const {canvas:a,
gb:c}of this.M)a.remove(),c.remove();this.M.length=0}wd(){return this.M[0].canvas}tc(a){return Math.min(a,this.M.length-1)}Nb(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].gb}He(){return fa&&"cordova"===this.A}nb(){const a=navigator.userAgent;return fa&&ta.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Fe(){return y}xd(){return y&&ta.has(this.A)}zd(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}Na(){return this.zd()||"xbox-uwp-webview2"===this.A}async Ed(a){this.ba&&!await ja()&&(this.ba=!1);"macos-wkwebview"===this.A?this.qb({type:"ready"}):this.Na()&&(this.hf(),this.le=(await this.We()).registeredComponentIds);if("playable-ad"===this.A){this.ra=self.c3_base64files;this.ac={};await this.Oe();for(let d=0,e=a.fb.length;d<e;++d){var c=a.fb[d];this.ac.hasOwnProperty(c)?a.fb[d]={uf:!0,yf:this.ac[c]}:this.ra.hasOwnProperty(c)&&(a.fb[d]=URL.createObjectURL(this.ra[c]))}a.pc=
[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Dc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.wf?this.aa=a.wf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Cf&&(this.Lb=a.Cf);c=new MessageChannel;this.ya=c.port1;this.ya.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.af(d));this.Ab=
new self.Ie(this);await va(this.Ab);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ba?await this.Ve(a,c.port2):await this.Ue(a,c.port2)}Gc(a){a=this.Lb.hasOwnProperty(a)?this.Lb[a]:a.endsWith("/workermain.js")&&this.Lb.hasOwnProperty("workermain.js")?this.Lb["workermain.js"]:"playable-ad"===
this.A&&this.ra.hasOwnProperty(a)?this.ra[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async rc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Yb)return a=await this.Mb(d.tf?a:this.cb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}oa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}vc(){return this.Na()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.A)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}Dd(a){var c=this.aa,d=location.href,e=this.oa(),f=this.ga(),g=this.vc(),
h=window.devicePixelRatio,k=b.mb(),l=a.Hf,p=window.cr_previewImageBlobs||this.ra,r=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,u=window.cr_swClientId||"";a=a.me;var ba=(new URLSearchParams(self.location.search)).has("debug"),G=this.Ab;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,cssDisplayMode:g,devicePixelRatio:h,isFullscreen:k,projectData:l,previewImageBlobs:p,previewProjectFileBlobs:r,previewProjectFileSWUrls:t,swClientId:u,exportType:a,isDebug:ba,
ife:!!self.Gf,jobScheduler:{inputPort:G.Vc,outputPort:G.ed,maxNumWorkers:G.mf},supportedAudioFormats:ka,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.cb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.cb+"opus.wasm.wasm",isFileProtocol:this.Yb,isiOSCordova:this.He(),isiOSWebView:this.nb(),isWindowsWebView2:this.zd(),isAnyWebView2Wrapper:this.Na(),wrapperComponentIds:this.le,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ve(a,c){const d=this.Gc(a.Bf);"preview"===
this.A?(this.va=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.va.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.va.addEventListener("message",r);this.va.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.va=await this.rc(d,this.aa,{type:"module",name:"Runtime",tf:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);
const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,gb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.pc||[],k=a.fb;h=await Promise.all(h.map(l=>this.Ra(l)));k=await Promise.all(k.map(l=>this.Ra(l)));if("cordova"===this.A)for(let l=0,p=a.oc.length;l<p;++l){const r=a.oc[l],t=r[0];if(t===a.od||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Ra(t)}this.va.postMessage(Object.assign(this.Dd(a),
{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.oc,mainProjectScript:a.od,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...wa(this.Ab)]);this.Va=E.map(l=>new l(this));this.Cd();xa(e);ya(g);za(this.ma);self.c3_callFunction=(l,p)=>{var r=this.ma;return r.m.Ad(r.tb,"js-invoke-function",{name:l,params:p})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.pb("runtime","go-to-last-error-script"))}async Ue(a,c){const d=
document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,gb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Va=E.map(h=>new h(this));this.Cd();xa(d);ya(e);e=a.fb.map(h=>"string"===typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.pc)){var f=[...a.pc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=
await Promise.all(e.map(h=>this.Ra(h)));await Promise.all(e.map(h=>z(h)));e=self.C3_ProjectScriptsStatus;f=a.od;const g=a.oc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Ra(k),await z(k),"preview"!==this.A||e[h]||this.Id(h,"main script did not run to completion")}catch(l){this.Id(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=await this.Ra(k),await z(k);"preview"===this.A&&"object"!==typeof self.Df.Ff?(this.Sb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Dd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:sa}),za(this.ma),this.Fd(),this.Xa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Xa,a))}Id(a,c){this.Sb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Fd(){this.Sb()}Sb(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ze(){const a=await Aa(this.Ab);return{outputPort:a,transferables:[a]}}ff(a){if(!this.Wc){var c=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,gb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Xd&&(g.style.display="",h.style.display=
"");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Xd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,gb:p}=this.M.pop();p.remove();this.ba&&!d?this.fd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),
this.ba?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,xa(c),ya(d),this.M.push({canvas:c,gb:d});for(const l of this.Va)if(l instanceof window.sc&&l.Ta)for(const p of l.Ia.values())e=l.m.tc(p.md),f=p.pa,-1!==
e&&-1!==f&&e!==f&&(f=p.wb,f.remove(),l.m.Nb(e).appendChild(f),p.pa=e);this.Mc();return{addedCanvases:a,transferables:k}}Xe(){for(const a of this.fd)a.remove();this.fd.length=0}Mc(){this.gd||(this.gd=!0,this.Dc(this.ke))}Re(){this.Hd(this.ke);this.gd=!1;let a=[];for(var c of this.Va)if(c instanceof window.sc){var d=c.Ta?[...c.Ia.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.pa,l=h.pa;return k!==l?k-l:g.yb-h.yb});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.pa!==c&&(this.Bd(c,a.slice(d,
e)),c=g.pa,d=e)}d<e&&this.Bd(c,a.slice(d,e))}Bd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.wb);var d=new Set(c);a=this.Nb(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Te(){if(this.ba)throw Error("not available in worker mode");return this.Xa}pb(a,c,d,e,f){this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}Ad(a,c,d,e,f){const g=ra++,h=new Promise((k,l)=>{qa.set(g,{resolve:k,reject:l})});this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.$e(a);if("result"===c)this.cf(a);else if("runtime-ready"===c)this.df();else if("alert-error"===c)this.Sb(),alert(a.message);else if("creating-runtime"===c)this.Fd();else throw Error(`unknown message '${c}'`);}$e(a){const c=a.component,d=a.handler,
e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Rb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Rb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Rb(f,!1,""+h)}):this.Rb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Rb(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.ya.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}cf(a){const c=a.responseId,d=a.isOk;a=a.result;const e=qa.get(c);d?e.resolve(a):e.reject(a);qa.delete(c)}B(a,c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static hb(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Cd(){for(const a of this.Va)if("runtime"===a.tb){this.ma=a;return}throw Error("cannot find runtime DOM handler");
}af(a){this.pb("debugger","message",a)}df(){for(const a of this.Va)a.qd()}static mb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ua)}static Jd(a){ua=!!a}Dc(a){this.Ib.add(a);this.Lc()}Hd(a){this.Ib.delete(a);0===this.Ib.size&&this.Ec()}Lc(){-1===this.bb&&0<this.Ib.size&&(this.bb=requestAnimationFrame(this.qf))}Ec(){-1!==this.bb&&(cancelAnimationFrame(this.bb),this.bb=-1)}bf(){this.bb=-1;for(const a of this.Ib)a();this.Lc()}Ea(a){this.ma.Ea(a)}Oa(a){this.ma.Oa(a)}Kc(){this.ma.Kc()}Qb(a){this.ma.Qb(a)}Ge(){return!!ka["audio/webm; codecs=opus"]}async jf(a){a=
await this.Ad("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ke(a){this.Wc=!0;this.Rd=a}Ee(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}yd(a){return!this.Ee(a)}async Ra(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Yb&&this.yd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Mb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ye(a){const c=a.filename;switch(a.as){case "text":return await this.De(c);
case "buffer":return await this.Mb(c);default:throw Error("unsupported type");}}td(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async De(a){a=await this.td(a);return await la(a)}Fc(){if(B.length&&!(8<=D)){D++;var a=B.shift();this.Pe(a.filename,a.zf,a.sf)}}Mb(a){return new Promise((c,d)=>{B.push({filename:a,zf:e=>{D--;this.Fc();c(e)},sf:e=>{D--;this.Fc();d(e)}});this.Fc()})}async Pe(a,c,d){try{const e=
await this.td(a),f=await ma(e);c(f)}catch(e){d(e)}}Gd(a){if("entered-fullscreen"===a)b.Jd(!0),H(this.ma);else if("exited-fullscreen"===a)b.Jd(!1),H(this.ma);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.nd(a),this.nd=null):"extension-message"===c?this.pb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}ef(a){this.qb({type:"extension-message",componentId:a.componentId,messageId:a.messageId,
params:a.params||[],asyncId:a.asyncId})}qb(a){this.Na()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}hf(){window.moveTo=(a,c)=>{this.qb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.qb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}We(){return this.Na()?new Promise(a=>{this.nd=a;this.qb({type:"wrapper-init"})}):
Promise.resolve()}async Oe(){const a=[];for(const [c,d]of Object.entries(this.ra))a.push(this.Ne(c,d));await Promise.all(a)}async Ne(a,c){if("object"===typeof c)this.ra[a]=new Blob([c.str],{type:c.type}),this.ac[a]=c.str;else{let d=await this.Se(c);d||(d=this.Qe(c));this.ra[a]=d}}async Se(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Qe(a){a=this.gf(a);return this.Me(a.data,a.vf)}gf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{vf:a,data:d}}Me(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const I=self.Pa,Ba=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ca={dispatchUserScriptEvent:!0},Da={dispatchRuntimeEvent:!0};function Ea(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}
function Fa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function Ga(b){b=URL.createObjectURL(b);try{return await Fa(b)}finally{URL.revokeObjectURL(b)}}function Ha(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ia=new Set(["input","textarea","datalist","select"]),Ja=new Set(["canvas","body","html"]);
function K(b){b.target.tagName&&Ja.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ka(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function La(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await Ga(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ga(b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ma=!1;document.addEventListener("pause",()=>Ma=!0);document.addEventListener("resume",()=>Ma=!1);function xa(b){b.addEventListener("selectstart",K);b.addEventListener("gesturehold",K);b.addEventListener("pointerdown",K)}function ya(b){b.addEventListener("selectstart",Ka);b.addEventListener("gesturehold",Ka);b.addEventListener("touchstart",Ka)}function za(b){b.Qd=!0;b.ad=b.m.oa();b.Bb=b.m.ga()}
function H(b){if(!b.ka){var a=I.mb();a&&"any"!==b.kd&&Na(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ga()})}}async function Oa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Qa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ra(b){return await self.C3_GetSvgImageSize(b.blob)}function Sa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ta(b){self.setTimeout(()=>{b.Pd=!0},1E3);"cordova"===b.m.A?(document.addEventListener("pause",()=>Ua(b,!0)),document.addEventListener("resume",()=>Ua(b,!1))):document.addEventListener("visibilitychange",()=>Ua(b,"hidden"===document.visibilityState));b.ec=!("hidden"!==document.visibilityState&&!Ma);return{isSuspended:b.ec}}
function Va(b){b.Ld||(b.Ld=!0,window.addEventListener("deviceorientation",a=>{b.ka||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.ka||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Wa(b){b.Kd||(b.Kd=!0,window.addEventListener("devicemotion",a=>{if(!b.ka){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Xa(b){await Ea(b.url)}
function Ya(b,a){b.Sd=a.message;-1===b.Qc&&(b.Qc=setTimeout(()=>{b.Qc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Sd)},250))}function Za(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:I.mb(),innerWidth:b.oa(),innerHeight:b.ga()})}
function Ua(b,a){b.ec!==a&&((b.ec=a)?b.m.Ec():b.m.Lc(),m(b,"visibilitychange",{hidden:a}),!a&&b.m.nb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function $a(b,a,c){"Backspace"===c.key&&K(c);"nwjs"===b.m.A&&"u"===c.key&&(c.ctrlKey||c.metaKey)&&c.preventDefault();if(!b.ka){var d=Ba.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},J)}}
function L(b,a,c,d){b.ka||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Ba,pageX:c.pageX,pageY:c.pageY+b.Ba,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function M(b,a,c){if(!b.ka){var d=0;"mouse"===c.pointerType&&(d=b.cd);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Ba,pageX:c.pageX,pageY:c.pageY+b.Ba,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},J);"mouse"===c.pointerType&&
(b.cd=c.buttons)}}function ab(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Ba=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Ba=a))}}
function bb(b,a,c,d){const e=b.oa(),f=b.ga();b.eb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.mb(),cssDisplayMode:b.m.vc()}):10>d&&cb(b,e,f,d+1)}function cb(b,a,c,d){-1!==b.eb&&clearTimeout(b.eb);b.eb=setTimeout(()=>bb(b,a,c,d),48)}
function Na(b){b=b.kd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function db(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.hb(class extends self.jb{constructor(b){super(b,"runtime");this.Qd=!1;this.eb=-1;this.kd="any";this.ec=this.Kd=this.Ld=!1;this.lc=document.createElement("div");this.lc.className="c3-screen-reader-text";this.lc.setAttribute("aria-live","polite");document.body.appendChild(this.lc);this.Ha=null;this.ka=!1;this.Sd="";this.Qc=-1;this.Pd=!1;this.ad=b.oa();this.Bb=b.ga();this.Ba=this.Kb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Oa(c));b.B("runtime","raster-svg-image",c=>Qa(c));b.B("runtime","get-svg-image-size",c=>Ra(c));b.B("runtime","set-target-orientation",c=>{this.kd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Sa(c));b.B("runtime","go-to-script",c=>Sa(c));b.B("runtime","before-start-ticking",()=>Ta(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ha||(this.Ha=document.createElement("div"),this.Ha.id="inspectOutline",document.body.appendChild(this.Ha));var d=this.Ha;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ha&&(this.Ha.style.display="none")});b.B("runtime","enable-device-orientation",()=>Va(this));b.B("runtime","enable-device-motion",()=>Wa(this));b.B("runtime","add-stylesheet",c=>Xa(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>{alert(c.message)});b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.lc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===
d?(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ka=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.m.wd().style.display="";this.m.Ke(c.duration)});b.B("runtime","export-to-video-progress",c=>Ya(this,c));b.B("runtime","exported-to-video",c=>{window.rf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.rf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ha(d)||c.preventDefault()});window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);window.addEventListener("touchstart",K,{passive:!1});window.addEventListener("pointerdown",K,{passive:!1});this.cd=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",La,{passive:!1});window.addEventListener("wheel",La,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ka&&this.Qd){var c=this.oa();var d=this.ga();if(this.m.xd()){if(this.Pd){if(this.ad===
c&&d<this.Bb){this.Kb=this.Bb-d;ab(this,this.Bb,this.Kb);c=void 0;break a}0<this.Kb&&(this.Kb=0,ab(this,d,this.Kb))}this.ad=c;this.Bb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.mb(),cssDisplayMode:this.m.vc()});this.m.nb()&&(-1!==this.eb&&clearTimeout(this.eb),bb(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",
()=>H(this));window.addEventListener("fullscreenerror",c=>Za(this,c));window.addEventListener("webkitfullscreenerror",c=>Za(this,c));window.addEventListener("mozfullscreenerror",c=>Za(this,c));if(b.nb()){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d});document.documentElement.setAttribute("ioswebview","")}this.Ya=new Set;this.cc=new WeakSet;this.xa=!1}qd(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,Da)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}m(this,"window-blur",{parentHasFocus:a},Da);this.cd=0});window.addEventListener("focusin",a=>{a=a.target;(Ia.has(a.tagName.toLowerCase())||Ha(a))&&m(this,"keyboard-blur",null,Da)});window.addEventListener("keydown",a=>$a(this,"keydown",a));window.addEventListener("keyup",a=>$a(this,"keyup",a));window.addEventListener("mousedown",a=>L(this,"mousedown",a,
Ca));window.addEventListener("mousemove",a=>L(this,"mousemove",a,Ca));window.addEventListener("mouseup",a=>L(this,"mouseup",a,Ca));window.addEventListener("dblclick",a=>L(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.ka||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Ba,pageX:a.pageX,pageY:a.pageY+this.Ba,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();
db(a.target)&&document.activeElement&&!db(document.activeElement)&&document.activeElement.blur();M(this,"pointerdown",a)});this.m.ba&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{M(this,"pointermove",a)}):window.addEventListener("pointermove",a=>M(this,"pointermove",a));window.addEventListener("pointerup",a=>M(this,"pointerup",a));window.addEventListener("pointercancel",a=>M(this,"pointercancel",a));const b=()=>this.Kc();window.addEventListener("pointerup",
b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.m.Fe()&&!this.m.xd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{ab(this,this.ga(),navigator.virtualKeyboard.boundingRect.height)}));this.m.nb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}oa(){return this.m.oa()}ga(){return this.m.ga()}Kc(){var b=
[...this.Ya];this.Ya.clear();if(!this.xa)for(const a of b)(b=a.play())&&b.catch(()=>{this.cc.has(a)||this.Ya.add(a)})}Ea(b){if("function"!==typeof b.play)throw Error("missing play function");this.cc.delete(b);let a;try{a=b.play()}catch(c){this.Ya.add(b);return}a&&a.catch(()=>{this.cc.has(b)||this.Ya.add(b)})}Oa(b){this.Ya.delete(b);this.cc.add(b)}Qb(b){this.xa=!!b}});"use strict";
async function va(b){if(b.kf)throw Error("already initialised");b.kf=!0;var a=b.za.Gc(("playable-ad"===b.za.A?b.za.cb:"")+"dispatchworker.js");b.Pc=await b.za.rc(a,b.sb,{name:"DispatchWorker"});a=new MessageChannel;b.Vc=a.port1;b.Pc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.ed=await Aa(b)}function wa(b){return[b.Vc,b.ed]}
async function Aa(b){const a=b.Yd.length;var c=b.za.Gc(("playable-ad"===b.za.A?b.za.cb:"")+"jobworker.js");c=await b.za.rc(c,b.sb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Pc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Yd.push(c);return e.port1}
self.Ie=class{constructor(b){this.za=b;this.sb=b.aa;this.sb="preview"===b.A?this.sb+"workers/":this.sb+b.cb;this.mf=Math.min(navigator.hardwareConcurrency||2,16);this.Pc=null;this.Yd=[];this.ed=this.Vc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.Pa({Af:!0,Bf:"workermain.js",fb:["scripts/c3runtime.js"],oc:[],od:"",xf:"scripts/",pc:[],me:"html5"}));"use strict";
self.Pa.hb(class extends self.jb{constructor(b){super(b,"mouse");v(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.m.wd().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";const eb=180/Math.PI;
async function fb(b,a){if(a.isiOSCordova||a.isSafari)b.hc=!0;b.ld=a.timeScaleMode;b.ce=["equalpower","HRTF","soundfield"][a.panningModel];b.Od=["linear","inverse","exponential"][a.distanceModel];b.de=a.refDistance;b.be=a.maxDistance;b.fe=a.rolloffFactor;if(b.m.Wc)b.hc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.m.Rd)});else{var c={latencyHint:a.latencyHint};b.ie||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");gb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&gb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ua=b.g.createGain();b.Ua.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ca);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>N(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function hb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Zd=g.slice(0);kb(b,g);try{b.R=await lb(b,c,d,e,g,f);if(p){O(b.R,!0);var u=b.R,ba=p.x,G=p.y,Cb=p.z,Db=p.angle,na=p.innerAngle,oa=p.outerAngle,pa=p.outerGain;if(u.zb){mb(u,ba,G,Cb,Db);var C=self.ib.Le;
u.sa[0]!==C(na)&&(u.sa[0]=C(na),u.F.coneInnerAngle=C(na));u.sa[1]!==C(oa)&&(u.sa[1]=C(oa),u.F.coneOuterAngle=C(oa));u.sa[2]!==pa&&(u.sa[2]=pa,u.F.coneOuterGain=pa)}p.hasOwnProperty("uid")&&(b.R.qa=p.uid)}else"number"===typeof r&&0!==r?(P(b.R,!0),nb(b.R,r)):(O(b.R,!1),P(b.R,!1));b.R.Play(h,k,l,t)}catch(Eb){console.error("[Construct] Audio: error starting playback: ",Eb);return}finally{c=g.join(" ");d=b.Hb.get(c);if(!d)throw Error("expected pending tag");d.pd--;0===d.pd&&(d.resolve(),b.Hb.delete(c))}w(b)}
async function ob(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await pb(b,c);for(const h of Q(b,c))if(!h.wa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.La=d;h.Wa=g;h.he=a}R(b)}async function qb(b,a){const c=a.tags;a=a.rate;await pb(b,c);for(const d of Q(b,c))d.la!==a&&(d.la=a,d.Fa())}async function rb(b,a){const c=a.tags;a=a.pos;await pb(b,c);for(const d of Q(b,c))d.zc(a)}
async function sb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await lb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function tb(b,a){if(a=await N(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function ub(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await N(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.se(b,...e);else if("delay"===c)d=new self.qe(b,...e);else if("convolution"===c){var g=d=new self.pe(b,f.ha,...e),h=a.bufferType;g.Md=a.bufferOriginalUrl;g.Nd=h}else if("flanger"===c)d=
new self.te(b,...e);else if("phaser"===c)d=new self.ve(b,...e);else if("gain"===c)d=new self.ue(b,...e);else if("stereopan"===c)d=new self.xe(b,...e);else if("tremolo"===c)d=new self.ye(b,...e);else if("ringmod"===c)d=new self.we(b,...e);else if("distortion"===c)d=new self.re(b,...e);else if("compressor"===c)d=new self.oe(b,...e);else if("analyser"===c)d=new self.ne(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ja.get(h);l||(l=[],g.ja.set(h,l));d.Wd=l.length;d.jd=
h;l.push(d);vb(g,h)}wb(b)}
async function xb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ca()&&1===c||!e.Ca()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ja.values())for(const g of f)g.j();b.ja.clear();b.mc=a.timeScale;b.Rc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ca[e]=d[e];b.g.listener.setOrientation(...b.ca)}b.xa=a.isSilent;b.m.Qb(b.xa);b.bc=a.masterVolume;b.Ua.gain.value=
b.bc;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>ub(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>yb(b,f,c)));R(b)}
async function zb(b,a){try{const c=b.g.suspend(a.time);b.Vd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.m.pb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Ab(d)),b.Vd=!0);await c}catch(c){Ab(c)}}
function gb(b){b.Wb||(b.Uc=!1,window.addEventListener("pointerup",b.Aa,!0),window.addEventListener("touchend",b.Aa,!0),window.addEventListener("click",b.Aa,!0),window.addEventListener("keydown",b.Aa,!0),b.Wb=!0)}
async function N(b,a,c,d,e,f){for(var g of b.ia)if(g.lb()===c)return await Bb(g),g;if(f)return null;if(e&&(b.hc||b.Ud)){f=0;for(let h=0,k=b.ia.length;h<k;++h)g=b.ia[h],b.ia[f]=g,g.Ca()?g.j():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.ie;e&&f&&(b.Ud=!0);c=!e||b.hc||f?new self.Be(b,a,c,d,e,f):new self.ze(b,a,c,d,e);b.ia.push(c);await Bb(c);b.ae.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.ae.add(a));return c}
function Fb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Gb(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.ea()}function vb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of Hb(b,a))e=f,d=c,e=e.da||e.F||e.G,e.disconnect(),e.connect(d);b.Ja&&b.bd===a&&(b.Ja.disconnect(),b.Ja.connect(c))}
function*Hb(b,a){if(a)for(const c of b.H)Fb(0<c.na.length?c.na[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Ib(b,a,c){return c?b.m.jf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Jb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*Q(b,a){if(0<a.length)for(const d of b.H){a:{b=d.na;var c=a;for(const e of c){c=!1;for(const f of b)if(Fb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function lb(b,a,c,d,e,f){for(const g of b.H)if(g.lb()===c&&(g.qc()||f))return g.na=e,g;a=await N(b,a,c,d,f);e="html5"===a.Nc?new self.Ae(a.u,a,e):new self.Ce(a.u,a,e);b.H.push(e);return e}
function kb(b,a){a=a.join(" ");let c=b.Hb.get(a);if(!c){let d=null;c={pd:0,promise:new Promise(e=>d=e),resolve:d};b.Hb.set(a,c)}c.pd++}function pb(b,a){return(b=b.Hb.get((0===a.length?b.Zd:a).join(" ")))?b.promise:Promise.resolve()}function R(b){if(0<b.Sa.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Kb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function wb(b){b.Xc||(b.Xc=!0,Promise.resolve().then(()=>Lb(b)))}
function Lb(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.kb());m(b,"fxstate",{fxstate:a});b.Xc=!1}
async function yb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await lb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(O(b,!0),e=b.F,f=d.pos,b.$a[0]=f[0],b.$a[1]=f[1],b.$a[2]=f[2],f=d.orient,b.Za[0]=f[0],b.Za[1]=f[1],b.Za[2]=f[2],e.setPosition(...b.$a),e.setOrientation(...b.Za),b.sa[0]=d.cia,b.sa[1]=d.coa,b.sa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.qa=d.uid):O(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?P(b,!1):(P(b,!0),nb(b,d));c.Play(k,l,p,0);a.isPlaying||c.ob();c.Ic(a)}}}function Ab(b){console.error("[Audio] Offline rendering error: ",b)}
self.ib=class extends self.jb{constructor(b){super(b,"audio");this.Ua=this.g=null;this.Wb=this.Uc=!1;this.Aa=()=>{if(!this.Uc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Wb&&(this.Uc=!0,window.removeEventListener("pointerup",this.Aa,!0),window.removeEventListener("touchend",this.Aa,!0),window.removeEventListener("click",this.Aa,!0),window.removeEventListener("keydown",
this.Aa,!0),this.Wb=!1)}};this.ia=[];this.H=[];this.R=null;this.Zd=[];this.ae=new Set;this.$d=-1;this.Hb=new Map;this.bc=1;this.xa=!1;this.ld=0;this.mc=1;this.Rc=0;this.ce="HRTF";this.Od="inverse";this.de=600;this.be=1E4;this.fe=1;this.$=[0,0,0];this.ca=[0,0,-1,0,1,0];this.Ud=this.hc=!1;this.ie=this.m.Ge();this.ja=new Map;this.Sa=new Set;this.Vd=this.Xc=!1;this.bd="";this.Ja=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ja&&this.Ja.disconnect();this.bd=c.toLowerCase();this.Ja=this.g.createMediaStreamSource(a);
this.Ja.connect(Gb(this,this.bd))};this.Vb=null;self.C3Audio_GetOutputStream=()=>{this.Vb||(this.Vb=this.g.createMediaStreamDestination(),this.Ua.connect(this.Vb));return this.Vb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>fb(this,a)],["play",a=>hb(this,a)],["stop",a=>{a=a.tags;for(const c of Q(this,a))c.Da()}],["stop-all",()=>{for(const a of this.H)a.Da()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of Q(this,c))a?d.ob():d.Pb();R(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of Q(this,c))S(d,a)}],["fade-volume",a=>ob(this,a)],["set-master-volume",a=>{this.bc=a.vol;this.Ua.gain.value=this.bc}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of Q(this,c))Mb(d,a)}],["set-silent",a=>{this.xa=a.isSilent;this.m.Qb(this.xa);for(const c of this.H)c.Tb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of Q(this,c))d.Ac(a)}],["set-playback-rate",a=>qb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of Q(this,
c))P(d,!0),nb(d,a)}],["seek",a=>rb(this,a)],["preload",a=>sb(this,a)],["unload",a=>tb(this,a)],["unload-all",()=>{for(const a of this.ia)a.j();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Bc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>ub(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ja.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);wb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ja.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ja.delete(a);vb(this,a)}}],["tick",a=>{this.mc=a.timeScale;this.Rc=a.gameTime;this.$d=a.tickCount;if(0!==this.ld)for(var c of this.H)c.Fa();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ca[0]!==
c[0]||this.ca[1]!==c[1]||this.ca[2]!==c[2]||this.ca[3]!==c[3]||this.ca[4]!==c[4]||this.ca[5]!==c[5])){for(let d=0;6>d;++d)this.ca[d]=c[d];this.g.listener.setOrientation(...this.ca)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.qa===a&&mb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>xb(this,a)],["offline-render-audio",a=>zb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Ua}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Ob(){return this.xa}Ea(b){this.m.Ea(b)}Oa(b){this.m.Oa(b)}Qa(){for(var b of this.Sa)b.Qa();
b=this.g.currentTime;for(var a of this.H)a.Qa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.kb());m(this,"state",{tickCount:this.$d,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Sa].map(c=>({tag:c.jd,index:c.Wd,peak:c.ab,rms:c.ee,binCount:c.l.frequencyBinCount,freqBins:c.Td}))});0===a.length&&0===this.Sa.size&&this.Xb&&(this.m.Hd(this.je),this.Xb=!1)}static Le(b){return b*eb}static vd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Je(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.Pa.hb(self.ib);"use strict";function Bb(b){b.$b||(b.$b=b.Hc());return b.$b}self.rd=class{constructor(b,a,c,d,e){this.u=b;this.pf=a;this.Ka=c;this.T=d;this.lf=e;this.Nc="";this.$b=null}j(){this.$b=this.u=null}Hc(){}V(){return this.u.V()}wc(){return this.pf}lb(){return this.Ka}uc(){return this.T}Ca(){return this.lf}fa(){}};"use strict";
self.ze=class extends self.rd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Nc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Cb=this.Db=null;this.L.addEventListener("canplaythrough",()=>!0);this.Gb=this.V().createGain();this.Fb=null;this.L.addEventListener("canplay",()=>{this.Db&&(this.Db(),this.Cb=this.Db=null);!this.Fb&&this.L&&(this.Fb=this.V().createMediaElementSource(this.L),this.Fb.connect(this.Gb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ka}' error: `,f);this.Cb&&(this.Cb(f),this.Cb=this.Db=null)})}j(){Jb(this.u,this);this.Gb.disconnect();this.Gb=null;this.Fb.disconnect();this.Fb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Hc(){return new Promise((b,a)=>{this.Db=b;this.Cb=a;this.L.src=this.Ka})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Nb(b){if(b.Ga)return b.Ga;var a=b.u.m;if("cordova"===a.A&&a.yd(b.Ka)&&a.Yb)b.Ga=await a.Mb(b.Ka);else{a=await fetch(b.Ka);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ga=await a.arrayBuffer()}}async function Ob(b){if(b.ha)return b.ha;b.ha=await Ib(b.u,b.Ga,b.nf);b.Ga=null}
self.Be=class extends self.rd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Nc="webaudio";this.ha=this.Ga=null;this.nf=!!f}j(){Jb(this.u,this);this.ha=this.Ga=null;super.j()}async Hc(){try{await Nb(this),await Ob(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ka}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Pb=0;
function O(b,a){a=!!a;b.zb!==a&&(b.zb=a,b.zb?(P(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.ce,b.F.distanceModel=b.u.Od,b.F.refDistance=b.u.de,b.F.maxDistance=b.u.be,b.F.rolloffFactor=b.u.fe),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function P(b,a){a=!!a;b.Zb!==a&&(b.Zb=a,b.Zb?(O(b,!1),b.da=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.da),b.da.connect(b.ea())):(b.da.disconnect(),b.da=null,b.G.disconnect(),b.G.connect(b.ea())))}function nb(b,a){b.Zb&&b.hd!==a&&(b.da.pan.value=a,b.hd=a)}function S(b,a){b.La=a;b.G.gain.cancelScheduledValues(0);b.Wa=-1;b.G.gain.value=b.xc()}function Mb(b,a){a=!!a;b.wa!==a&&(b.wa=a,b.Tb())}
function mb(b,a,c,d,e){if(b.zb){var f=b.$a,g=b.Za,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function T(b){return b.Zc?b.u.Rc:performance.now()/1E3}
self.sd=class{constructor(b,a,c){this.u=b;this.P=a;this.na=c;this.Ub=Pb++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.zb=!1;this.$a=[0,0,0];this.Za=[0,0,0];this.sa=[0,0,0];this.da=null;this.Zb=!1;this.hd=0;this.I=!0;this.Y=this.ta=this.J=!1;this.La=1;this.wa=!1;this.la=1;b=this.u.ld;this.Zc=1===b&&!this.Ca()||2===b;this.Wa=this.qa=-1;this.he=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.da&&(this.da.disconnect(),this.da=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ea(){return Gb(this.u,0<this.na.length?this.na[0]:"")}wc(){return this.P.wc()}lb(){return this.P.lb()}uc(){return this.P.uc()}Ca(){return this.P.Ca()}O(){}qc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Ma(){}fa(){return this.P.fa()}Play(){}Da(){}ob(){}Pb(){}Qa(b){-1!==this.Wa&&b>=this.Wa&&(this.Wa=-1,this.he&&this.Da(),Kb(this.u,"fade-ended",this.na,this.Ub))}xc(){const b=this.La;return isFinite(b)?b:0}Ob(){return this.u.Ob()}Tb(){}Ac(){}Fa(){}zc(){}Bc(){}yc(){}kb(){var b=
this.Ub,a=this.na,c=this.fa(),d=-1===this.Wa?this.La:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.$a,orient:this.Za,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.qa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ma(),playbackRate:this.la,uid:this.qa,bufferOriginalUrl:this.wc(),bufferUrl:"",bufferType:this.uc(),isMusic:this.Ca(),isLooping:this.Y,isMuted:this.wa,resumePosition:this.yc(),pan:f,stereoPan:this.da?
this.hd:null}}Ic(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Fa());Mb(this,b.isMuted)}};"use strict";
self.Ae=class extends self.sd{constructor(b,a,c){super(b,a,c);this.P.Gb.connect(this.G);this.P.onended=()=>this.Jc()}j(){this.Da();this.P.Gb.disconnect();super.j()}W(){return this.P.W()}Jc(){this.I=!0;this.qa=-1;Kb(this.u,"ended",this.na,this.Ub)}O(){return this.W().ended}qc(){return this.I?!0:this.O()}Ma(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);S(this,a);this.wa=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.lb()}' to position '${c}': `,e)}this.u.Ea(d);this.J=this.I=!1;this.Y=b;this.la=1}Da(){const b=this.W();b.paused||b.pause();this.u.Oa(b);this.I=!0;this.J=!1;this.qa=-1}ob(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.Oa(b);this.J=!0}}Pb(){!this.J||this.I||this.O()||(this.u.Ea(this.W()),this.J=!1)}Tb(){this.W().muted=this.wa||this.Ob()}Ac(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Fa(){let b=this.la;this.Zc&&(b*=this.u.mc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}zc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}yc(){return this.Ma()}Bc(b){b?this.IsPlaying()?(this.W().pause(),this.ta=!0):this.ta=!1:this.ta&&(this.u.Ea(this.W()),this.ta=!1)}};"use strict";
function U(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.rb=null}
self.Ce=class extends self.sd{constructor(b,a,c){super(b,a,c);this.s=null;this.dc=d=>this.Jc(d);this.Tc=!0;this.rb=null;this.S=this.fc=this.ic=0;this.dd=1}j(){this.Da();U(this);this.dc=null;super.j()}Jc(b){this.J||this.ta||b.target!==this.rb||(this.I=this.Tc=!0,this.qa=-1,U(this),Kb(this.u,"ended",this.na,this.Ub))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Tc}qc(){return!this.s||this.I?!0:this.O()}Ma(){let b;b=this.J?this.S:this.fc+(T(this)-this.ic)*this.la;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.wa=!1;this.dd=1;S(this,a);U(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ha;this.s.connect(this.G);this.rb=this.s;this.s.onended=this.dc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Tc=!1;this.Y=b;this.la=1;this.ic=T(this);this.fc=c}Da(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.qa=-1}ob(){this.J||this.I||this.O()||(this.S=this.Ma(),this.Y&&(this.S%=this.fa()),this.J=!0,this.s.stop(0))}Pb(){!this.J||this.I||this.O()||(U(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.rb=this.s,this.s.onended=this.dc,this.s.loop=this.Y,S(this,this.La),this.Fa(),this.s.start(0,this.S),this.ic=T(this),this.fc=this.S,this.J=!1)}xc(){return super.xc()*this.dd}Tb(){this.dd=this.wa||this.Ob()?0:1;S(this,this.La)}Ac(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Fa(){let b=this.la;this.Zc&&(b*=this.u.mc);this.s&&(this.s.playbackRate.value=b)}zc(b){this.I||this.O()||(this.J?this.S=b:(this.ob(),
this.S=b,this.Pb()))}yc(){return this.S}Bc(b){b?this.IsPlaying()?(this.ta=!0,this.S=this.Ma(),this.Y&&(this.S%=this.fa()),this.s.stop(0)):this.ta=!1:this.ta&&(U(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.rb=this.s,this.s.onended=this.dc,this.s.loop=this.Y,S(this,this.La),this.Fa(),this.s.start(0,this.S),this.ic=T(this),this.fc=this.S,this.ta=!1)}Ic(b){super.Ic(b);this.S=b.resumePosition}};"use strict";function V(b){return b.g.createGain()}
function W(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class X{constructor(b){this.u=b;this.g=b.V();this.Wd=-1;this.T=this.jd="";this.o=null}j(){this.g=null}N(){}U(){}kb(){return{type:this.T,tag:this.jd,params:this.o}}}
self.se=class extends X{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.v=V(this);this.i=V(this);this.i.gain.value=g;this.h=V(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}j(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;W(this,this.i.gain,a,c,d);W(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;W(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;W(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;W(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,W(this,this.D.gain,a,c,d)}}};
self.qe=class extends X{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.v=V(this);this.i=V(this);this.i.gain.value=d;this.h=V(this);this.h.gain.value=1-d;this.Eb=V(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.vb=V(this);this.vb.gain.value=c;this.v.connect(this.Eb);this.v.connect(this.h);this.Eb.connect(this.i);this.Eb.connect(this.X);this.X.connect(this.vb);this.vb.connect(this.Eb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.Eb.disconnect();
this.X.disconnect();this.vb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.ib.vd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;W(this,this.i.gain,a,c,d);W(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);W(this,this.vb.gain,e(a),c,d);break;case 5:this.o[0]=a,W(this,this.X.delayTime,a,c,d)}}};
self.pe=class extends X{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Nd=this.Md="";this.v=V(this);this.i=V(this);this.i.gain.value=d;this.h=V(this);this.h.gain.value=1-d;this.ub=this.g.createConvolver();this.ub.normalize=c;this.ub.buffer=a;this.v.connect(this.ub);this.v.connect(this.h);this.ub.connect(this.i)}j(){this.v.disconnect();this.ub.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,W(this,this.i.gain,a,c,d),W(this,this.h.gain,1-a,c,d)}}kb(){const b=super.kb();b.bufferOriginalUrl=this.Md;b.bufferUrl="";b.bufferType=this.Nd;return b}};
self.te=class extends X{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.v=V(this);this.h=V(this);this.h.gain.value=1-f/2;this.i=V(this);this.i.gain.value=f/2;this.xb=V(this);this.xb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=V(this);this.K.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.xb);this.xb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.xb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;W(this,this.i.gain,a/2,c,d);W(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;W(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;W(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,W(this,this.xb.gain,a/100,c,d)}}};
self.ve=class extends X{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.v=V(this);this.h=V(this);this.h.gain.value=1-g/2;this.i=V(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=V(this);this.K.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;W(this,this.i.gain,a/2,c,d);W(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;W(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;W(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;W(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;W(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,W(this,this.C.frequency,a,c,d)}}};self.ue=class extends X{constructor(b,a){super(b);this.T="gain";this.o=[a];this.l=V(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.ib.vd;switch(b){case 4:this.o[0]=e(a),W(this,this.l.gain,e(a),c,d)}}};
self.xe=class extends X{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,W(this,this.l.pan,a,c,d)}}};
self.ye=class extends X{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.l=V(this);this.l.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=V(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.l.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;W(this,this.l.gain,1-a/2,c,d);W(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,W(this,this.C.frequency,a,c,d)}}};
self.we=class extends X{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.v=V(this);this.i=V(this);this.i.gain.value=c;this.h=V(this);this.h.gain.value=1-c;this.Jb=V(this);this.Jb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Jb.gain);this.C.start(0);this.v.connect(this.Jb);this.v.connect(this.h);this.Jb.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Jb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;W(this,this.i.gain,a,c,d);W(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,W(this,this.C.frequency,a,c,d)}}};
self.re=class extends X{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.v=V(this);this.kc=V(this);this.jc=V(this);b=d;.01>b&&(b=.01);this.kc.gain.value=b;this.jc.gain.value=Math.pow(1/b,.6)*e;this.i=V(this);this.i.gain.value=f;this.h=V(this);this.h.gain.value=1-f;this.nc=this.g.createWaveShaper();this.Oc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Oc[32768+e]=f,this.Oc[32768-
e-1]=-f;this.nc.curve=this.Oc;this.v.connect(this.kc);this.v.connect(this.h);this.kc.connect(this.nc);this.nc.connect(this.jc);this.jc.connect(this.i)}j(){this.v.disconnect();this.kc.disconnect();this.nc.disconnect();this.jc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,W(this,this.i.gain,a,c,d),W(this,this.h.gain,
1-a,c,d)}}};self.oe=class extends X{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.ne=class extends X{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Td=new Float32Array(this.l.frequencyBinCount);this.ge=new Uint8Array(a);this.ee=this.ab=0;b=this.u;b.Sa.add(this);R(b)}j(){this.u.Sa.delete(this);this.l.disconnect();super.j()}Qa(){this.l.getFloatFrequencyData(this.Td);this.l.getByteTimeDomainData(this.ge);const b=this.l.fftSize;let a=this.ab=0;for(var c=0;c<b;++c){let d=(this.ge[c]-
128)/128;0>d&&(d=-d);this.ab<d&&(this.ab=d);a+=d*d}c=self.ib.Je;this.ab=c(this.ab);this.ee=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";let Qb=!1;async function Rb(b){var a=Sb(b.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:b.duration,startDelay:0,weakMagnitude:b.weakMag,strongMagnitude:b.strongMag})}catch(c){console.warn("[Gamepad] Failed to vibrate gamepad: ",c)}}
function Y(){try{return Array.from(navigator.getGamepads()).filter(b=>b&&b.connected)}catch(b){return Qb||(console.warn("[Construct] Failed to access gamepads: ",b),Qb=!0),[]}}function Tb(b){-1===b.ua&&(b.ua=setInterval(()=>Ub(b),4))}function Ub(b){var a=Y();a.length&&(a=a.map(c=>({index:c.index,id:c.id,buttons:c.buttons.map(d=>({pressed:d.pressed,value:d.value})),axes:c.axes})),m(b,"input-update",a))}function Sb(b){for(const a of Y())if(a.index===b)return a;return null}
self.Pa.hb(class extends self.jb{constructor(b){super(b,"gamepad");this.Yc=!1;this.ua=-1;q(this,"ready",()=>{this.Yc=!0;for(const a of Y())m(this,"gamepad-connected",{index:a.index,id:a.id});Tb(this)});q(this,"vibrate",a=>Rb(a));q(this,"reset-vibrate",a=>{(a=Sb(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});q(this,"suspend",()=>{-1!==this.ua&&(clearInterval(this.ua),this.ua=-1)});q(this,"resume",()=>{Tb(this)});window.addEventListener("gamepadconnected",a=>{this.Yc&&(a=a.gamepad,m(this,
"gamepad-connected",{index:a.index,id:a.id}))});window.addEventListener("gamepaddisconnected",a=>{this.Yc&&m(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of Y()){const c=a.vibrationActuator;c&&c.reset&&c.reset()}})}});"use strict";function Z(b){b.stopPropagation()}
self.Pa.hb(class extends self.sc{constructor(b){super(b)}ud(b,a){const c=document.createElement("progress");c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",Z);c.addEventListener("pointerrawupdate",Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",Z);c.addEventListener("click",()=>{var d;d||(d={});d.elementId=b;n(this,"click",d)});a.id&&(c.id=
a.id);a.className&&(c.className=a.className);this.Cc(c,a);return c}Cc(b,a){b.title=a.title;const c=a.value;a=a.max;0<a&&0<=c?(b.max=a,b.value=c):(b.removeAttribute("value"),b.removeAttribute("max"))}});
